apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applicationboundary.rgds.yaml
  - cephfsaddon.rgds.yaml
  - cephfsvolumebinding.rgds.yaml
  - cinderstoragebinding.rgds.yaml
  - endpointbinding.rgds.yaml
  - gpuruntimeaddon.rgds.yaml
  - hubauthbinding.rgds.yaml
  - s3csiaddon.rgds.yaml
  - s3volumebinding.rgds.yaml
  - secretbundle.rgds.yaml
