apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - binderbuildinstance.rgds.yaml
  - jupyterhubinstance.rgds.yaml
  - jupyteroutpostinstance.rgds.yaml
  - monitoringinstance.rgds.yaml
  - registrycacheinstance.rgds.yaml
  - smokeapplication.rgds.yaml
