apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterfoundation.yaml
  - machineprofile.rgds.yaml
  - spokeaccount.rgds.yaml
  - spokenetwork.rgds.yaml
  - spokenodepool.rgds.yaml
  - spokeregistration.rgds.yaml
  - workloadcluster.rgds.yaml
