apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - identity/csoc-identity.rgd.yaml
  - network/auto-allocated-spoke-network.rgd.yaml
  - network/dedicated-spoke-network.rgd.yaml
  - cluster/spoke-cluster.rgd.yaml
  - apps/spoke-policy.rgd.yaml
  - apps/cluster-registration.rgd.yaml
  - apps/hello-app.rgd.yaml
