apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - test-poc/cluster/v1/spoke-cluster.rgd.yaml
  - test-poc/cluster/v1/spoke-identity.rgd.yaml
  - test-poc/configmaps/immutable-spoke-config.rgd.yaml
  - test-poc/configmaps/spoke-environment-config.rgd.yaml
  - test-poc/configmaps/spoke-network-import-config.rgd.yaml
  - test-poc/configmaps/spoke-shared-network-config.rgd.yaml
  - test-poc/compute/spoke-server-group.rgd.yaml
  - test-poc/network/auto-allocated-spoke-network.rgd.yaml
  - test-poc/network/dedicated-spoke-network.rgd.yaml
  - test-poc/network/imported-spoke-network.rgd.yaml
  - test-poc/network/isolated-openstack-network.rgd.yaml
  - test-poc/network/routed-spoke-network.rgd.yaml
  - test-poc/network/fully-managed-spoke-network.rgd.yaml
  - test-poc/network/shared-provider-network.rgd.yaml
  - test-poc/security/spoke-security-group.rgd.yaml
  - test-poc/storage/spoke-volume.rgd.yaml
  - test-poc/workloads/hello-app.rgd.yaml
