apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - csoc-identity-config.yaml
  - spoke-policy.yaml
  - spoke-identity.yaml
  - cluster-registration.yaml
  - hello-app.yaml
