apiVersion: v1
kind: Service
metadata:
  name: hello-csoc
  namespace: hello-csoc
  labels:
    app: hello-csoc
    csoc.js2.org/managed: "true"
spec:
  selector:
    app: hello-csoc
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
