apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: spokeidentity
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
    kro.run/description: Restricted OpenStack account identity and spoke namespace boundary
spec:
  schema:
    apiVersion: v1alpha1
    group: csoc.js2.org
    kind: SpokeIdentity
    scope: Cluster
    additionalPrinterColumns:
      - name: Namespace
        type: string
        jsonPath: .status.namespace
      - name: Ready
        type: boolean
        jsonPath: .status.ready
    spec:
      credentialPolicy: string | default="restricted" enum="restricted"
    status:
      ready: '${accountnamespace.?status.?phase.orValue("") == "Active" && cloudconfigsecret.metadata.name != "" && workloadcloudconfigsecret.metadata.name != ""}'
      credentialsReady: '${cloudconfigsecret.metadata.name != "" && workloadcloudconfigsecret.metadata.name != ""}'
      namespace: ${accountnamespace.metadata.name}
      identityName: ${openstackidentity.metadata.name}
      projectID: ${trustedaccountconfig.data.projectID}
      capoSecretName: '${schema.metadata.name + "-cloud-config"}'
      workloadSecretName: '${schema.metadata.name + "-workload-cloud-config"}'
  resources:
    - id: trustedaccountconfig
      externalRef:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-account-config"}'
          namespace: '${"spokeconfig-" + schema.metadata.name}'
    - id: trustedcomputeconfig
      externalRef:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-compute-service-config"}'
          namespace: '${"spokeconfig-" + schema.metadata.name}'
    - id: trustednetworkserviceconfig
      externalRef:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-network-service-config"}'
          namespace: '${"spokeconfig-" + schema.metadata.name}'
    - id: trustedstorageconfig
      externalRef:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-storage-service-config"}'
          namespace: '${"spokeconfig-" + schema.metadata.name}'
    - id: trustedloadbalancerconfig
      externalRef:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-loadbalancer-service-config"}'
          namespace: '${"spokeconfig-" + schema.metadata.name}'
    - id: trustedkubernetesconfig
      externalRef:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-kubernetes-config"}'
          namespace: '${"spokeconfig-" + schema.metadata.name}'
    - id: accountnamespace
      readyWhen:
        - '${accountnamespace.?status.?phase.orValue("") == "Active"}'
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: '${"spokeclusters-" + schema.metadata.name}'
          labels:
            csoc.js2.org/managed: "true"
            csoc.js2.org/openstack-credentials: allowed
            csoc.js2.org/credential-policy: ${schema.spec.credentialPolicy}
            csoc.js2.org/identity: ${schema.metadata.name}
            csoc.js2.org/openstack-project-id: ${trustedaccountconfig.data.projectID}
    - id: accountconfig
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-account-config"}'
          namespace: ${accountnamespace.metadata.name}
        immutable: true
        data: ${trustedaccountconfig.data}
    - id: computeconfig
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-compute-service-config"}'
          namespace: ${accountnamespace.metadata.name}
        immutable: true
        data: ${trustedcomputeconfig.data}
    - id: networkserviceconfig
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-network-service-config"}'
          namespace: ${accountnamespace.metadata.name}
        immutable: true
        data: ${trustednetworkserviceconfig.data}
    - id: storageconfig
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-storage-service-config"}'
          namespace: ${accountnamespace.metadata.name}
        immutable: true
        data: ${trustedstorageconfig.data}
    - id: loadbalancerconfig
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-loadbalancer-service-config"}'
          namespace: ${accountnamespace.metadata.name}
        immutable: true
        data: ${trustedloadbalancerconfig.data}
    - id: kubernetesconfig
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: '${schema.metadata.name + "-kubernetes-config"}'
          namespace: ${accountnamespace.metadata.name}
        immutable: true
        data: ${trustedkubernetesconfig.data}
    - id: cloudconfigsecret
      externalRef:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '${schema.metadata.name + "-cloud-config"}'
          namespace: ${accountnamespace.metadata.name}
    - id: workloadcloudconfigsecret
      externalRef:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '${schema.metadata.name + "-workload-cloud-config"}'
          namespace: ${accountnamespace.metadata.name}
    - id: openstackidentity
      template:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: OpenStackClusterIdentity
        metadata:
          name: ${schema.metadata.name}
        spec:
          namespaceSelector:
            matchLabels:
              csoc.js2.org/identity: ${schema.metadata.name}
          secretRef:
            name: '${schema.metadata.name + "-cloud-config"}'
            namespace: ${accountnamespace.metadata.name}
    - id: accountpolicy
      template:
        apiVersion: admissionregistration.k8s.io/v1
        kind: ValidatingAdmissionPolicy
        metadata:
          name: '${"spokecluster-restrictions-" + schema.metadata.name + ".csoc.js2.org"}'
        spec:
          failurePolicy: Fail
          paramKind:
            apiVersion: csoc.js2.org/v1alpha1
            kind: SpokeIdentity
          matchConstraints:
            resourceRules:
              - apiGroups: [csoc.js2.org]
                apiVersions: [v1alpha1]
                operations: [CREATE, UPDATE]
                resources: [spokeclusters]
          validations:
            - expression: object.spec.kubernetes.minNodes <= object.spec.kubernetes.maxNodes
              message: minimum workers must not exceed maximum workers
            - expression: object.spec.kubernetes.minNodes >= 1
              message: minimum workers is 1
            - expression: object.spec.kubernetes.maxNodes <= 4
              message: maximum workers is 4
    - id: accountpolicybinding
      template:
        apiVersion: admissionregistration.k8s.io/v1
        kind: ValidatingAdmissionPolicyBinding
        metadata:
          name: '${"spokecluster-account-restrictions-" + schema.metadata.name}'
        spec:
          policyName: ${accountpolicy.metadata.name}
          paramRef:
            name: ${schema.metadata.name}
            parameterNotFoundAction: Deny
          matchResources:
            namespaceSelector:
              matchLabels:
                csoc.js2.org/identity: ${schema.metadata.name}
          validationActions:
            - Deny
